title: Avika's CSA Personal Blog 
description: "Class of 2027"
owner_name: Avika Prasad
github_username: avikaprasad22 
github_repo: "avika_csa" 
baseurl: "/avika_csa" 
future: true
# remote_theme: jekyll/minima
theme: minima
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/open-coding-society" }
    - { platform: x, user_url: "https://x.com/Open_Coding" }
    - { platform: youtube, user_url: "https://www.youtube.com/@OpenCodingSociety" } 
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
header_pages:
  - navigation/blog.md
  - navigation/search.md
  - navigation/about.md
  - navigation/logintoolkit.md